### ISSUE TITLE
老铁，有图的题目没图呀

### ISSUE THREAD

**Issue by jiqing112** [doupoa/DrivingTestSubjectOne#1]
RT

**Comment by doupoa** [comment]
命令行你怎么输出图片
检索脚本在开发时定义为快速检索，本不需输出图片。对于题目相同图片不同的题目，特意定为输出问题的答案及技巧。无论如何技巧是不会重复的。请自行根据输出的技巧及当前题目判断正确结果。
原始数据中有图片链接，若有必要请自行修改检索脚本。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月18日(周日) 凌晨0:37
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [doupoa/DrivingTestSubjectOne] 老铁，有图的题目没图呀 (Issue #1)




 
RT

**Comment by jiqing112** [comment]
不好意思 没仔细看json ，感谢分享。
